### ISSUE TITLE
Inquiry on Model Inclusion Criteria

### ISSUE THREAD

**Issue by gustrd** [Haidra-Org/AI-Horde-text-model-reference#3]
Hello team,

I'm a big fan of your work! 

I'm curious about the criteria for including a model here. Could you provide some insights?

**Comment by henk717** [comment]
If we can legally host the model on our backends it can be included. There are to many models so the reason it seems random is because we add them on request by our community.

**Comment by gustrd** [comment]
Nice, were can the requests be made?

**Comment by henk717** [comment]
https://koboldai.org/discord or trough a PR (In case of a PR it would have to be in all 3 positions with the right prefixes and kudo's amount)

**Comment by gustrd** [comment]
Thanks!
